#ifndef CONFIG_H
#define CONFIG_H

#define KERNEL_CODE_SELECTOR 0x08
#define KERNEL_DATA_SELECTOR 0x10

#define HEVOS_TOTAL_INTERRUPTS 512

// 100 MB heap size
#define HEVOS_HEAP_SIZE_BYTES       104857600
#define HEVOS_HEAP_BLOCK_SIZE       4096
#define HEVOS_HEAP_ADDRESS          0x01000000
#define HEVOS_HEAP_TABLE_ADDRESS    0x00007E00

#define HEVOS_SECTOR_SIZE 512

#define HEVOS_MAX_FILESYSTEMS 12
#define HEVOS_MAX_FILE_DESCRIPTORS 512

#define HEVOS_MAX_PATH 108

#define HEVOS_TOTAL_GDT_SEGMENTS 6

#define HEVOS_PROGRAM_VIRTUAL_ADDRESS 0x400000
#define HEVOS_USER_PROGRAM_STACK_SIZE 1024 * 16 
#define HEVOS_PROGRAM_VIRTUAL_STACK_ADDRESS_START 0x3FF000
#define HEVOS_PROGRAM_VIRTUAL_STACK_ADDRESS_END HEVOS_PROGRAM_VIRTUAL_STACK_ADDRESS_START - HEVOS_USER_PROGRAM_STACK_SIZE

#define HEVOS_USER_DATA_SEGMENT 0x23
#define HEVOS_USER_CODE_SEGMENT 0x1b

#define HEVOK_MAX_PROGRAM_ALLOCATIONS 1024

#define HEVOS_MAX_PROCESSES 12

#define HEVOS_MAX_ISR80H_COMMANDS 1024

#define HEVOS_KEYBOARD_BUFFER_SIZE 1024

#endif